
Couldn't find processed data. Processing...
Epsilon: 0.15
Example No: 0 Label: 95
Traceback (most recent call last):
  File "/home/ayberk/PycharmProjects/FederatedFP/fingerprinting.py", line 103, in fingerprinting
    first_loss = alpha * tf.reshape(tf.keras.losses.categorical_crossentropy([1.0, 0.0], [ensemble_output[tf.argmax(source_prediction, 1)], 1.0 - ensemble_output[tf.argmax(source_prediction, 1)]]), ())
  File "/home/ayberk/PycharmProjects/FederatedFP/venv/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/ayberk/PycharmProjects/FederatedFP/venv/lib/python3.9/site-packages/tensorflow/python/ops/array_ops.py", line 907, in _check_index
    raise TypeError(_SLICE_TYPE_ERROR + ", got {!r}".format(idx))
